name: Rust LOC + CFP Analysis (Network I/O, Async Excluded)

on:
  workflow_dispatch:       # Manual trigger
  schedule:
    - cron: "0 3 * * 1"    # Optional: every Monday at 03:00 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git
          cargo install tokei

      - name: Prepare work directory
        run: mkdir -p work

      - name: Clone repos and run tokei
        run: |
          echo "repo,rust_files,rust_code,rust_comments,rust_blanks" > rust_loc_results.csv
          while read -r repo; do
            [[ -z "$repo" ]] && continue
            echo "Processing $repo..."
            dir="work/$(echo "$repo" | tr / _)"
            git clone --depth 1 "$repo" "$dir" --quiet || continue
            tokei "$dir" --output json > "$dir/tokei.json"
            python3 scripts/parse_tokei_network.py "$repo" "$dir/tokei.json" >> rust_loc_results.csv
          done < repos.txt

      - name: Estimate CFP with Network I/O
        run: python3 scripts/analyze_loc_cfp_network.py

      - name: Upload LOC + CFP + Summary
        uses: actions/upload-artifact@v4
        with:
          name: rust-loc-cfp-network
          path: rust_loc_results_with_network.csv
