name: Rust LOC + CFP Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"  # optional: run every Monday at 03:00 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git
          cargo install tokei

      - name: Prepare work directory
        run: mkdir -p work

      - name: Clone repos and run tokei
        run: |
          echo "repo,rust_files,rust_code,rust_comments,rust_blanks" > rust_loc_results.csv
          while read -r repo; do
            [[ -z "$repo" ]] && continue
            echo "Processing $repo..."
            dir="work/$(echo "$repo" | tr / _)"
            git clone --depth 1 "https://github.com/$repo.git" "$dir" --quiet || continue
            tokei "$dir" --output json > "$dir/tokei.json"
            python3 scripts/parse_tokei.py "$repo" "$dir/tokei.json"
          done < repos.txt >> rust_loc_results.csv

      - name: Estimate CFP and Summary Stats
        run: python3 scripts/analyze_loc_cfp.py

      - name: Upload LOC + CFP + Summary
        uses: actions/upload-artifact@v4
        with:
          name: rust-loc-cfp-summary
          path: rust_loc_results_with_summary.csv
