name: Rust LOC Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git
          cargo install tokei

      - name: Prepare work directory
        run: mkdir -p work

      - name: Clone repos and run tokei
        run: |
          while read -r repo; do
            [[ -z "$repo" ]] && continue
            echo "Processing $repo..."
            dir="work/$(echo "$repo" | tr / _)"
            git clone --depth 1 "https://github.com/$repo.git" "$dir" --quiet || continue
            tokei "$dir" --output json > "$dir/tokei.json"
          done < repos.txt

      - name: Process JSON to CSV
        run: python3 process_tokei.py

      - name: Upload LOC results
        uses: actions/upload-artifact@v4
        with:
          name: rust-loc-results
          path: rust_loc_results.csv
